### ISSUE TITLE
it's really slow...

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#13]
... how do we speed it up?

**Comment by stevevance** [comment]
This is most likely because it is showing all of the existing transit lines data at once, instead of contextually. 

We should do two things:
1. Simplify the geometry of the existing transit lines data using a simplify plugin in QGIS
2. Show the existing transit lines at certain zoom levels. 

_How to show existing transit lines at certain zoom levels_
You'll need an "event trigger" and a callback function. What happens is that you set an event trigger to watch for the Leaflet event called `zoomend` and that trigger calls the callback function. So, every time the map finishes zooming to a new zoom level, your callback function is triggered. 

This function will (1) check the current zoom level, and (2) depending on if that zoom level is a desired one, the transit lines are added to the map, and (2) if that zoom level is not the desired one, the transit lines are removed from the map.

**Comment by yfreemark** [comment]
Simplification:
I think this will be good too. I am trying to use SimpliPy, but I have never used this before. Have you? The problem is basically that though I am able to do the simplification, in the process, I lose all my data attached to the lines. Do you know how to have it simplify AND take with it the database backing it? I think I'm missing some crucial step here.

Showing things at certain zoom levels:
- I have no idea how to do this! Can you help me?

**Comment by yfreemark** [comment]
I figured out how to deal with the SimpliPy problem, so that's resolved. The existing lines file is down to 408 kb.

The grand total of the other files, not including the existing stops, is 407 kb. That seems really small. Am I wrong? Nonetheless, the website still cannot handle it. Am I missing something? Sadly, if the map is unable to handle this, I'm going to have to use Google maps--but I'm open to suggestions.

**Comment by yfreemark** [comment]
OK, I think the way to deal with this is as follows (hopefully this works...):
- have the system load only the under construction, and renovating files at first.
- when you zoom in, add the funded/ns, future, and existing files. [at zoom level 9 AND NEVER AT LOWER LEVELS 0-8]
- when you zoom in to level 13, add the existing stop file. [AND NEVER AT LOWER LEVELS 0-12]

Can you help me do this?

**Comment by stevevance** [comment]
The big problem was that ALL data was being added twice (you couldn't see it because features would be atop each other). This was just lazy coding on my part.
