### ISSUE TITLE
The repository doesn't have a license file. 

### ISSUE THREAD

**Issue by Kakurady** [stevevance/ttp-2016-transit-investments#31]
First, thank you for sharing the code and the data on GitHub! <3

I noticed there's no COPYING or LICENSE.txt in the repository. Specifying a license makes it clear under what conditions people can use the code and data for. 

The data are probably under their own license which may have attribution requirements. As for code, Github has a help page about choosing a license: https://help.github.com/articles/open-source-licensing/

**Comment by stevevance** [comment]
@yfreemark What kind of license would you like to apply to the codebase?

As far as geographic (`.geojson` files) data goes, some of what we used on the site comes from OpenStreetMap, and we'll list which parts in the README. Other geographic data comes from United States Government sources, so that's public domain.

**Comment by yfreemark** [comment]
What do you recommend? I am fine with the MIT license
